# Use postgres/example user/password credentials

services:

  db:
    image: postgres:18.1
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
    - ./db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    - ../test/data/demo-20250901-3m.sql.gz:/data/demo-20250901-3m.sql.gz
    - ../test/data/:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: root123
      SCOREBOARDS_PASSWORD: test123
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - 5432:5432
